# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/vivado_tutorial/project_3/project_3.srcs/sources_1/bd/axi_bram_bd/ip/axi_bram_bd_axi_bram_ctrl_0_0/axi_bram_bd_axi_bram_ctrl_0_0.xci
# IP: The module: 'axi_bram_bd_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/vivado_tutorial/project_3/project_3.gen/sources_1/bd/axi_bram_bd/ip/axi_bram_bd_axi_bram_ctrl_0_0/axi_bram_bd_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_bram_bd_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/vivado_tutorial/project_3/project_3.srcs/sources_1/bd/axi_bram_bd/ip/axi_bram_bd_axi_bram_ctrl_0_0/axi_bram_bd_axi_bram_ctrl_0_0.xci
# IP: The module: 'axi_bram_bd_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/vivado_tutorial/project_3/project_3.gen/sources_1/bd/axi_bram_bd/ip/axi_bram_bd_axi_bram_ctrl_0_0/axi_bram_bd_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_bram_bd_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
