# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/axi_bram_bd/axi_bram_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_bram_bd || ORIG_REF_NAME==axi_bram_bd} -quiet] -quiet

# IP: bd/axi_bram_bd/ip/axi_bram_bd_processing_system7_0_0/axi_bram_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_bram_bd_processing_system7_0_0 || ORIG_REF_NAME==axi_bram_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/axi_bram_bd/ip/axi_bram_bd_proc_sys_reset_0_0/axi_bram_bd_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_bram_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==axi_bram_bd_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/axi_bram_bd/ip/axi_bram_bd_axi_bram_ctrl_0_0/axi_bram_bd_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_bram_bd_axi_bram_ctrl_0_0 || ORIG_REF_NAME==axi_bram_bd_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/axi_bram_bd/ip/axi_bram_bd_blk_mem_gen_0_0/axi_bram_bd_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_bram_bd_blk_mem_gen_0_0 || ORIG_REF_NAME==axi_bram_bd_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/axi_bram_bd/ip/axi_bram_bd_axi_smc_0/axi_bram_bd_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_bram_bd_axi_smc_0 || ORIG_REF_NAME==axi_bram_bd_axi_smc_0} -quiet] -quiet

# IP: bd/axi_bram_bd/ip/axi_bram_bd_axi_gpio_0_0/axi_bram_bd_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_bram_bd_axi_gpio_0_0 || ORIG_REF_NAME==axi_bram_bd_axi_gpio_0_0} -quiet] -quiet

# IP: bd/axi_bram_bd/ip/axi_bram_bd_riscv_bram_wrapper_0_0/axi_bram_bd_riscv_bram_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_bram_bd_riscv_bram_wrapper_0_0 || ORIG_REF_NAME==axi_bram_bd_riscv_bram_wrapper_0_0} -quiet] -quiet

# IP: bd/axi_bram_bd/ip/axi_bram_bd_axi_bram_ctrl_0_1/axi_bram_bd_axi_bram_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_bram_bd_axi_bram_ctrl_0_1 || ORIG_REF_NAME==axi_bram_bd_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/axi_bram_bd/ip/axi_bram_bd_blk_mem_gen_0_1/axi_bram_bd_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_bram_bd_blk_mem_gen_0_1 || ORIG_REF_NAME==axi_bram_bd_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/axi_bram_bd/ip/axi_bram_bd_jtag_axi_0_0/axi_bram_bd_jtag_axi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_bram_bd_jtag_axi_0_0 || ORIG_REF_NAME==axi_bram_bd_jtag_axi_0_0} -quiet] -quiet

# XDC: c:/vivado_tutorial/project_3/project_3.gen/sources_1/bd/axi_bram_bd/axi_bram_bd_ooc.xdc
